name: Selenium CI
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installer Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Vérifier Chrome
        run: google-chrome --version

      - name: Load repository
        uses: actions/checkout@master

      - name: Debug structure
        run: ls -R

      - name: Installation des dépendances
        run: mvn clean install -DskipTests

      - name: Exécuter les tests Selenium
        run: mvn test

